import React, { useState } from 'react';
import axios from 'axios';
import { Upload, FileAudio, Loader2, CheckCircle, Download, Mail, BarChart3, AlertCircle } from 'lucide-react';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

function App() {
  const [file, setFile] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [analysis, setAnalysis] = useState(null);
  const [error, setError] = useState(null);
  const [progress, setProgress] = useState('');

  const handleFileChange = (e) => {
    const selectedFile = e.target.files[0];
    if (selectedFile) {
      // Validate file size (200MB)
      if (selectedFile.size > 200 * 1024 * 1024) {
        setError('File size must be less than 200MB');
        return;
      }
      setFile(selectedFile);
      setError(null);
    }
  };

  const handleUpload = async () => {
    if (!file) return;
    
    setUploading(true);
    setError(null);
    setProgress('Uploading file...');
    
    try {
      const formData = new FormData();
      formData.append('file', file);
      
      setProgress('Transcribing audio...');
      
      const response = await axios.post(`${API_URL}/api/analyze`, formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
        },
        timeout: 300000, // 5 minutes timeout
      });
      
      setProgress('Analyzing meeting...');
      setAnalysis(response.data);
      setProgress('');
    } catch (err) {
      console.error('Error:', err);
      setError(err.response?.data?.detail || 'Failed to process recording. Please try again.');
    } finally {
      setUploading(false);
      setProgress('');
    }
  };

  const downloadMOM = () => {
    if (!analysis) return;

    const mom = `
MINUTES OF MEETING
Date: ${new Date().toLocaleDateString()}
Duration: ${analysis.duration}
Participants: ${analysis.participants.join(', ')}

EXECUTIVE SUMMARY:
${analysis.summary}

KEY DECISIONS:
${analysis.key_decisions.map((d, i) => `${i + 1}. ${d}`).join('\n')}

ACTION ITEMS:
${analysis.action_items.map((item, i) => 
  `${i + 1}. ${item.task}\n   Owner: ${item.owner}\n   Deadline: ${item.deadline}`
).join('\n\n')}

PRESENTATION STRENGTHS:
${analysis.strengths.map((s, i) => `${i + 1}. ${s}`).join('\n')}

AREAS FOR IMPROVEMENT:
${analysis.improvements.map((imp, i) => `${i + 1}. ${imp}`).join('\n')}

FULL TRANSCRIPT:
${analysis.transcript}

---
Generated by Meeting Analyzer on ${new Date().toLocaleString()}
    `.trim();

    const blob = new Blob([mom], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `meeting-minutes-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const emailToClient = () => {
    if (!analysis) return;
    
    const subject = encodeURIComponent('Meeting Minutes - ' + new Date().toLocaleDateString());
    const body = encodeURIComponent(`
Hi,

Please find the minutes from our recent meeting below:

Summary: ${analysis.summary}

Key Decisions:
${analysis.key_decisions.map((d, i) => `${i + 1}. ${d}`).join('\n')}

Action Items:
${analysis.action_items.map((item, i) => 
  `${i + 1}. ${item.task} (Owner: ${item.owner}, Deadline: ${item.deadline})`
).join('\n')}

Best regards
    `);
    
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 p-6">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold text-white mb-2">Meeting Analyzer</h1>
          <p className="text-purple-200">Upload recordings, get insights & meeting minutes</p>
        </div>

        {/* Upload Section */}
        <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-8 mb-6 border border-white/20">
          <div className="flex flex-col items-center">
            <label className="w-full cursor-pointer">
              <div className="border-2 border-dashed border-purple-300 rounded-xl p-12 text-center hover:border-purple-400 transition-colors">
                <Upload className="w-16 h-16 mx-auto mb-4 text-purple-300" />
                <p className="text-white text-lg mb-2">
                  {file ? file.name : 'Click to upload or drag and drop'}
                </p>
                <p className="text-purple-200 text-sm">MP3, WAV, M4A (max 200MB)</p>
                <input
                  type="file"
                  className="hidden"
                  accept="audio/*"
                  onChange={handleFileChange}
                />
              </div>
            </label>

            {error && (
              <div className="mt-4 p-4 bg-red-500/20 border border-red-500/50 rounded-lg flex items-center gap-2 text-red-200">
                <AlertCircle className="w-5 h-5" />
                <p>{error}</p>
              </div>
            )}

            {progress && (
              <div className="mt-4 p-4 bg-blue-500/20 border border-blue-500/50 rounded-lg flex items-center gap-2 text-blue-200">
                <Loader2 className="w-5 h-5 animate-spin" />
                <p>{progress}</p>
              </div>
            )}

            {file && !uploading && !analysis && (
              <button
                onClick={handleUpload}
                className="mt-6 px-8 py-3 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-lg font-semibold hover:from-purple-600 hover:to-pink-600 flex items-center gap-2"
              >
                <FileAudio className="w-5 h-5" />
                Analyze Recording
              </button>
            )}
          </div>
        </div>

        {/* Results Section */}
        {analysis && (
          <div className="space-y-6">
            {/* Quick Actions */}
            <div className="flex gap-4 justify-center flex-wrap">
              <button
                onClick={downloadMOM}
                className="px-6 py-3 bg-green-500 text-white rounded-lg font-semibold hover:bg-green-600 flex items-center gap-2"
              >
                <Download className="w-5 h-5" />
                Download Minutes
              </button>
              <button 
                onClick={emailToClient}
                className="px-6 py-3 bg-blue-500 text-white rounded-lg font-semibold hover:bg-blue-600 flex items-center gap-2"
              >
                <Mail className="w-5 h-5" />
                Email to Client
              </button>
            </div>

            {/* Meeting Info */}
            <div className="bg-white/10 backdrop-blur-lg rounded-xl p-6 border border-white/20">
              <div className="flex items-center gap-2 mb-4">
                <BarChart3 className="w-6 h-6 text-purple-300" />
                <h2 className="text-2xl font-bold text-white">Meeting Overview</h2>
              </div>
              <div className="grid grid-cols-2 gap-4 text-white">
                <div>
                  <p className="text-purple-200 text-sm">Duration</p>
                  <p className="font-semibold">{analysis.duration}</p>
                </div>
                <div>
                  <p className="text-purple-200 text-sm">Sentiment</p>
                  <p className="font-semibold capitalize">{analysis.sentiment}</p>
                </div>
              </div>
              <div className="mt-4">
                <p className="text-purple-200 text-sm mb-2">Participants</p>
                <div className="flex flex-wrap gap-2">
                  {analysis.participants.map((p, i) => (
                    <span key={i} className="px-3 py-1 bg-purple-500/30 rounded-full text-white text-sm">
                      {p}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Summary */}
            <div className="bg-white/10 backdrop-blur-lg rounded-xl p-6 border border-white/20">
              <h3 className="text-xl font-bold text-white mb-3">Executive Summary</h3>
              <p className="text-purple-100">{analysis.summary}</p>
            </div>

            {/* Presentation Feedback */}
            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-green-500/10 backdrop-blur-lg rounded-xl p-6 border border-green-500/30">
                <div className="flex items-center gap-2 mb-4">
                  <CheckCircle className="w-6 h-6 text-green-400" />
                  <h3 className="text-xl font-bold text-white">Presentation Strengths</h3>
                </div>
                <ul className="space-y-2">
                  {analysis.strengths.map((s, i) => (
                    <li key={i} className="text-green-100 flex gap-2">
                      <span className="text-green-400">•</span>
                      <span>{s}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="bg-orange-500/10 backdrop-blur-lg rounded-xl p-6 border border-orange-500/30">
                <div className="flex items-center gap-2 mb-4">
                  <BarChart3 className="w-6 h-6 text-orange-400" />
                  <h3 className="text-xl font-bold text-white">Areas for Improvement</h3>
                </div>
                <ul className="space-y-2">
                  {analysis.improvements.map((imp, i) => (
                    <li key={i} className="text-orange-100 flex gap-2">
                      <span className="text-orange-400">•</span>
                      <span>{imp}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Key Decisions */}
            <div className="bg-white/10 backdrop-blur-lg rounded-xl p-6 border border-white/20">
              <h3 className="text-xl font-bold text-white mb-4">Key Decisions</h3>
              <ul className="space-y-2">
                {analysis.key_decisions.map((decision, i) => (
                  <li key={i} className="text-purple-100 flex gap-2">
                    <span className="text-purple-400 font-bold">{i + 1}.</span>
                    <span>{decision}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Action Items */}
            <div className="bg-white/10 backdrop-blur-lg rounded-xl p-6 border border-white/20">
              <h3 className="text-xl font-bold text-white mb-4">Action Items</h3>
              <div className="space-y-4">
                {analysis.action_items.map((item, i) => (
                  <div key={i} className="bg-white/5 rounded-lg p-4 border border-white/10">
                    <p className="text-white font-semibold mb-2">{item.task}</p>
                    <div className="flex gap-4 text-sm flex-wrap">
                      <span className="text-purple-200">Owner: <span className="text-white">{item.owner}</span></span>
                      <span className="text-purple-200">Deadline: <span className="text-white">{item.deadline}</span></span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Transcript */}
            <div className="bg-white/10 backdrop-blur-lg rounded-xl p-6 border border-white/20">
              <h3 className="text-xl font-bold text-white mb-4">Full Transcript</h3>
              <div className="bg-slate-900/50 rounded-lg p-4 max-h-96 overflow-y-auto">
                <p className="text-purple-100 text-sm leading-relaxed whitespace-pre-wrap">{analysis.transcript}</p>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default App;